### PR TITLE
replace all skycoin/teller to amltoken/teller

### PR DESCRIPTION
**Pull request by ZSM5J**

### CODE REVIEW

**Comment by gz-c** [comment]
Needs to be formatted with goimports

Can use make install-linters to install goimports

Run make check before pushing

**Comment by iketheadore** [comment]
Do `dep ensure github.com/skycoin/teller`, don't change import paths, otherwise you have to change the paths every time when you need to pulling latest code from skycoin/teller

**Comment by gz-c** [comment]
@iketheadore it will be more effort to rewrite this as a library than to fix import merge conflicts

**Comment by ZSM5J** [comment]
after "make check" i get a lot of import errors, how can i fix it?

**Comment by gz-c** [comment]
@ZSM5J you have to paste the errors, we cannot guess what error you have

**Comment by ZSM5J** [comment]
gometalinter --disable-all -E goimports --tests --vendor ./...
cmd/proxy/proxy.go:1::warning: file is not goimported (goimports)
cmd/teller/teller.go:1::warning: file is not goimported (goimports)
src/proxy/http.go:1::warning: file is not goimported (goimports)
src/service/service_test.go:1::warning: file is not goimported (goimports)
src/service/btcaddrs/btcaddrs.go:1::warning: file is not goimported (goimports)
src/service/btcaddrs/btcaddrs_test.go:1::warning: file is not goimported (goimports)
src/service/btcaddrs/store.go:1::warning: file is not goimported (goimports)
src/service/btcaddrs/store_test.go:1::warning: file is not goimported (goimports)
src/service/exchange/exchange.go:1::warning: file is not goimported (goimports)
src/service/exchange/exchange_test.go:1::warning: file is not goimported (goimports)
src/service/exchange/store.go:1::warning: file is not goimported (goimports)
src/service/exchange/store_test.go:1::warning: file is not goimported (goimports)
src/service/monitor/monitor.go:1::warning: file is not goimported (goimports)
src/service/monitor/monitor_test.go:1::warning: file is not goimported (goimports)
src/service/scanner/scan_service.go:1::warning: file is not goimported (goimports)
src/service/scanner/scanner_test.go:1::warning: file is not goimported (goimports)
src/service/scanner/store.go:1::warning: file is not goimported (goimports)
src/service/scanner/store_test.go:1::warning: file is not goimported (goimports)
src/service/sender/send_service.go:1::warning: file is not goimported (goimports)
src/service/sender/send_service_test.go:1::warning: file is not goimported (goimports)
Makefile:19: recipe for target 'lint' failed
make: *** [lint] Error 1

**Comment by gz-c** [comment]
`make install-linters` will install `goimports`

Then do `goimports -w src/`

You can make your editor do this automatically on save

**Comment by ZSM5J** [comment]
i also do goimports -w cmd/
Now after "make check":
gometalinter --disable-all -E goimports --tests --vendor ./...
vendorcheck ./...
go test ./cmd/...
 github.com/skycoin/teller/cmd/proxy
cmd/proxy/proxy.go:97:17: cannot use auth (type *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/daemon".Auth) as type *"github.com/skycoin/teller/src/daemon".Auth in argument to proxy.New
github.com/skycoin/teller/cmd/teller
cmd/teller/teller.go:158:11: cannot use dummyBtcScanner literal (type *dummyBtcScanner) as type "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".BtcScanner in assignment:
        *dummyBtcScanner does not implement "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".BtcScanner (wrong type for GetDepositValue method)
                have GetDepositValue() <-chan "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/scanner".DepositNote
                want GetDepositValue() <-chan "github.com/skycoin/teller/src/service/scanner".DepositNote
cmd/teller/teller.go:159:11: cannot use dummySkySender literal (type *dummySkySender) as type "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".SkySender in assignment:
        *dummySkySender does not implement "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".SkySender (wrong type for SendAsync method)
                have SendAsync(string, int64, *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".SendOption) (<-chan interface {}, error)
                want SendAsync(string, int64, *"github.com/skycoin/teller/src/service/sender".SendOption) (<-chan interface {}, error)
cmd/teller/teller.go:191:11: cannot use "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/scanner".NewScanner(scanServ) (type *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/scanner".Scanner) as type "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".BtcScanner in assignment:
        *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/scanner".Scanner does not implement "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".BtcScanner (wrong type for GetDepositValue method)
                have GetDepositValue() <-chan "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/scanner".DepositNote
                want GetDepositValue() <-chan "github.com/skycoin/teller/src/service/scanner".DepositNote
cmd/teller/teller.go:196:46: cannot use skyCli (type *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/cli".Cli) as type "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".skyclient in argument to "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".NewService:
        *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/cli".Cli does not implement "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".skyclient (wrong type for GetTransaction method)
                have GetTransaction(string) (*"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/cli".TxJSON, error)
                want GetTransaction(string) (*"github.com/skycoin/teller/src/service/cli".TxJSON, error)
cmd/teller/teller.go:204:11: cannot use "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".NewSender(sendServ) (type *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".Sender) as type "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".SkySender in assignment:
        *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".Sender does not implement "github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".SkySender (wrong type for SendAsync method)
                have SendAsync(string, int64, *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/sender".SendOption) (<-chan interface {}, error)
                want SendAsync(string, int64, *"github.com/skycoin/teller/src/service/sender".SendOption) (<-chan interface {}, error)
cmd/teller/teller.go:230:38: cannot use auth (type *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/daemon".Auth) as type *"github.com/skycoin/teller/src/daemon".Auth in argument to service.New
cmd/teller/teller.go:243:19: cannot use excCli (type *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".Client) as type monitor.DepositStatusGetter in argument to monitor.New:
        *"github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".Client does not implement monitor.DepositStatusGetter (wrong type for GetDepositStatusDetail method)
                have GetDepositStatusDetail("github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange".DepositFilter) ([]"github.com/skycoin/teller/src/daemon".DepositStatusDetail, error)
                want GetDepositStatusDetail("github.com/skycoin/teller/src/service/exchange".DepositFilter) ([]"github.com/skycoin/teller/src/daemon".DepositStatusDetail, error)
Makefile:15: recipe for target 'test' failed
make: *** [test] Error 2

**Comment by gz-c** [comment]
`github.com/skycoin/teller`
This is the wrong folder, you should be in `github.com/amltoken/teller`

`github.com/skycoin/teller/vendor/github.com/amltoken/teller/src/service/exchange`
You have `github.com/amltoken/teller` vendored into `github.com/skycoin/teller`

**Comment by ZSM5J** [comment]
omg), fail was in folder where i keep project, now all works! big thanks

**Comment by gz-c** [comment]
The tests failed again, but it is not your fault, sometimes this test

```
2017/10/05 09:08:12 session.go:58: Handling msg type PING
--- FAIL: TestRunService (27.09s)
    --- FAIL: TestRunService/pong_timeout (22.03s)
    	service_test.go:69: Closing daemon.Session
    	leaktest.go:90: leaktest: timed out checking goroutines
FAIL
FAIL	github.com/amltoken/teller/src/service	27.099s
```

fails, sometimes it doesn't.

OK to merge

**Pull request merged**
